sudo: false

language: php

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

matrix:
  include:
    - php: 7.1
      env: WP_VERSION=latest
    - php: 7.0
      env: WP_VERSION=latest
    - php: 5.6
      env: WP_VERSION=4.4
    - php: 5.6
      env: WP_VERSION=latest
    - php: 5.6
      env: WP_VERSION=trunk
    - php: 5.6
      env: WP_TRAVISCI=phpcs
    - php: 5.3
      env: WP_VERSION=latest

before_script:
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - |
    if [[ ! -z "$WP_VERSION" ]]; then
      cp .env.dist .env
      COMPOSER_MEMORY_LIMIT=-1 travis_retry composer install-wp-tests
      COMPOSER_MEMORY_LIMIT=-1 travis_retry composer install
    fi
  - |
    if [[ "$WP_TRAVISCI" == "phpcs" ]]; then
      composer global require wp-coding-standards/wpcs
      phpcs --config-set installed_paths $HOME/.composer/vendor/wp-coding-standards/wpcs
    fi

script:
  - |
    if [[ ! -z "$WP_VERSION" ]]; then
      vendor/bin/codecept run wpunit
    fi
  - |
    if [[ "$WP_TRAVISCI" == "phpcs" ]]; then
      phpcs --standard=phpcs.ruleset.xml $(find . -name '*.php')
    fi
